{
    "openapi": "3.0.0",
    "info": {
        "title": "Medical",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:4000"
        }
    ],
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer"
            }
        }
    },
    "security": [
        {
            "bearerAuth": []
        }
    ],
    "tags": [
        {
            "name": "Auth",
            "supplier": "Supplier"
        }
    ],
    "paths": {
        "/api/auth/sign-up": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Sign up",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "firstName": "test",
                                    "lastName": "user",
                                    "userEmail": "test.user@example.com",
                                    "userPassword": "securePassword123",
                                    "userRole": "Client",
                                    "phoneNumber": "+1234567890",
                                    "address": "123 Main St, Springfield",
                                    "age": 0,
                                    "gender" : "Male",
                                    "client": {
                                        "bmi": 22.5,
                                        "bloodGroup": "O+",
                                        "medicalHistory": "No significant history",
                                        "allergies": "None",
                                        "age": 30
                                      },
                                      "nutritionist": {
                                            "specialization": "",
                                            "experienceYears": 0,
                                            "age": "",
                                            "gender": ""
                                      },
                                      "yogaTrainer": {
                                        "specialization": "",
                                        "experienceYears": 0,
                                        "age": "",
                                        "gender": ""
                                      }
                                  }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/api/auth/sign-in": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Sign in",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "userEmail": "",
                                    "userPassword": "",
                                    "isLong": true
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/api/auth/forgot-password": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Forget password",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "userEmail": ""
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/api/auth/reset-password": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Reset password",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                        "newPassword": "",
                                        "resetToken": ""
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/api/company/users": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Get Users",
                "parameters": [
                   {
                    "name": "include.role",
                    "in": "query",
                    "schema": {
                        "type": "client"
                    }
                   }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/api/company/appointment": {
            "post": {
                "tags": [
                    "Appointment"
                ],
                "summary": "Appointment Book",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                      "clientId": 0,
                                      "professionalId": 0,
                                      "appointmentDate": "2024-11-25",
                                      "appointmentFee": 0,
                                      "time": "",
                                      "professionType" : "YogaTrainer"
                                  }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "Appointment"
                ],
                "parameters": [
                    {
                      "name": "filter.nutritionistId",
                      "in": "query",
                      "required": false,
                      "schema": {
                        "type": "number"
                      }
                    },
                    {
                      "name": "filter.appointmentId",
                      "in": "query",
                      "required": false,
                      "schema": {
                        "type": "number"
                      }
                    },
                    {
                      "name": "filter.clientId",
                      "in": "query",
                      "required": false,
                      "schema": {
                        "type": "number"
                      }
                    },
                    {
                        "name": "filter.yogaTrainerId",
                        "in": "query",
                        "required": false,
                        "schema": {
                          "type": "number"
                        }
                      }
              ],
                "summary": "Appointment fetch",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/api/company/appointment/{appointmentId}": {
            "get": {
                "tags": [
                    "Appointment"
                ],
                "parameters": [
                    {
                        "name": "appointmentId",
                        "in": "path",
                        "required": true,
                        "schema": {
                          "type": "number"
                        }
                      }
                ],
                "summary": "Appointment by Id",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/api/company/diet-plan/{appointmentId}/{clientId}/{nutritionistId}": {
            "post": {
                "tags": [
                    "dietPlan"
                ],
                "parameters": [
                    {
                        "name": "appointmentId",
                        "in": "path",
                        "required": true,
                        "schema": {
                          "type": "number"
                        }
                      },
                      {
                        "name": "clientId",
                        "in": "path",
                        "required": true,
                        "schema": {
                          "type": "number"
                        }
                      },
                      {
                        "name": "nutritionistId",
                        "in": "path",
                        "required": true,
                        "schema": {
                          "type": "number"
                        }
                      }
                ],
                "summary": "Nutritionist DietPlan",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "breakfast": [
                                        {
                                            "food": "Oatmeal",
                                            "quantity": "200g",
                                            "calories": 150
                                        },
                                        {
                                            "food": "Boiled Eggs",
                                            "quantity": "2",
                                            "calories": 140
                                        }
                                    ],
                                    "lunch": [
                                        {
                                            "food": "Grilled Chicken",
                                            "quantity": "250g",
                                            "calories": 300
                                        },
                                        {
                                            "food": "Steamed Vegetables",
                                            "quantity": "150g",
                                            "calories": 100
                                        }
                                    ],
                                    "eveningSnack": [
                                        {
                                            "food": "Apple",
                                            "quantity": "1 medium",
                                            "calories": 95
                                        }
                                    ],
                                    "dinner": [
                                        {
                                            "food": "Salmon",
                                            "quantity": "200g",
                                            "calories": 280
                                        },
                                        {
                                            "food": "Brown Rice",
                                            "quantity": "150g",
                                            "calories": 180
                                        }
                                    ]
                                }
                                
                                  
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/api/company/diet-plan": {
            "get": {
                "tags": [
                    "dietPlan"
                ],
                "parameters": [
                      {
                        "name": "filter.appointmentId",
                        "in": "query",
                        "required": false,
                        "schema": {
                          "type": "number"
                        }
                      }

                ],
                "summary": "Nutritionist DietPlan",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/api/company/client-signup/{userId}": {
            "post": {
                "tags": [
                    "Client"
                ],
                "parameters": [
                      {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "schema": {
                          "type": "number"
                        }
                      }
                ],
                "summary": "Client signup",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    
                                        "bmi": 22.5,
                                        "bloodGroup": "A+",
                                        "medicalHistory": "History of hypertension and asthma.",
                                        "medications": "Lisinopril, Salbutamol",
                                        "surgeries": "Appendectomy in 2015",
                                        "height": 175.5,
                                        "weight": 70.5,
                                        "physicalActivity": "Moderate exercise 3 times a week",
                                        "smoking": false,
                                        "drinking": true,
                                        "allergies": "Peanuts, Penicillin",
                                        "pcod": false,
                                        "diabetes": false,
                                        "bloodPressure": true,
                                        "majorSurgery": "Knee replacement in 2020"
                                      
                                      
                                  }
                                  
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/api/company/client/{userId}": {
            "put": {
                "tags": [
                    "Client"
                ],
                "parameters": [
                      {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "schema": {
                          "type": "number"
                        }
                      }
                ],
                "summary": "Client Update",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    
                                        "bmi": 22.5,
                                        "bloodGroup": "A+",
                                        "medicalHistory": "History of hypertension and asthma.",
                                        "medications": "Lisinopril, Salbutamol",
                                        "surgeries": "Appendectomy in 2015",
                                        "height": 170.5,
                                        "weight": 70.5,
                                        "physicalActivity": "Moderate exercise 3 times a week",
                                        "smoking": false,
                                        "drinking": true,
                                        "allergies": "Peanuts, Penicillin",
                                        "pcod": false,
                                        "diabetes": false,
                                        "bloodPressure": true,
                                        "majorSurgery": "Knee replacement in 2020"
                                      
                                      
                                  }
                                  
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/api/company/exercise-plan/{appointmentId}/{clientId}/{yogaTrainerId}": {
            "post": {
                "tags": [
                    "Exercise Plan"
                ],
                "parameters": [
                    {
                        "name": "appointmentId",
                        "in": "path",
                        "required": true,
                        "schema": {
                          "type": "number"
                        }
                      },
                      {
                        "name": "clientId",
                        "in": "path",
                        "required": true,
                        "schema": {
                          "type": "number"
                        }
                      },
                      {
                        "name": "yogaTrainerId",
                        "in": "path",
                        "required": true,
                        "schema": {
                          "type": "number"
                        }
                      }
                ],
                "summary": "Exercise plan",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "morningExercise": [
                                      {
                                        "exerciseName": "Yoga Pose 1",
                                        "duration": "30 minutes",
                                        "frequency": "Daily"
                                      },
                                      {
                                        "exerciseName": "Yoga Pose 2",
                                        "duration": "20 minutes",
                                        "frequency": "Alternate Days"
                                      }
                                    ],
                                    "afternoonExercise": [
                                      {
                                        "exerciseName": "Yoga Pose 3",
                                        "duration": "45 minutes",
                                        "frequency": "Every Alternate Day"
                                      }
                                    ],
                                    "eveningExercise": [
                                      {
                                        "exerciseName": "Yoga Pose 4",
                                        "duration": "30 minutes",
                                        "frequency": "Daily"
                                      }
                                    ],
                                    "nightExercise": [
                                      {
                                        "exerciseName": "Yoga Pose 5",
                                        "duration": "20 minutes",
                                        "frequency": "Every Day"
                                      }
                                    ]
                                  }
                                               
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/api/company/exercise-plan": {
            "get": {
                "tags": [
                    "Exercise Plan"
                ],
                "parameters": [
                      {
                        "name": "filter.appointmentId",
                        "in": "query",
                        "required": false,
                        "schema": {
                          "type": "number"
                        }
                      }
                ],
                "summary": "Exercise Plan",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/api/company/subscription": {
            "post": {
                "tags": [
                    "Subscription Plan"
                ],
                "summary": "Subscription Plan",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                        "userId": 0,
                                        "planName": "Premium",
                                        "duration": ""
                                  }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "Subscription Plan"
                ],
                "parameters": [
                      {
                        "name": "userId",
                        "in": "path",
                        "required": false,
                        "schema": {
                          "type": "number"
                        }
                      }
                ],
                "summary": "Subscription Plan",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/api/company/user/{userId}": {
            "put": {
                "tags": [
                    "User"
                ],
                "parameters": [
                      {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "schema": {
                          "type": "number"
                        }
                      }
                ],
                "summary": "User Update",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "firstName": "test",
                                    "lastName": "test2",
                                    "phoneNumber": "+1234567890",
                                    "address": "123 Main St",
                                    "age": 0,
                                    "gender": "",
                                        "bmi": 24777.5,
                                        "bloodGroup": "O+",
                                        "medicalHistory": "Asthma, seasonal allergies",
                                        "medications": "Albuterol, Loratadine",
                                        "surgeries": "Appendectomy",
                                        "height": 175.5,
                                        "weight": 70.2,
                                        "physicalActivity": "Moderate",
                                        "smoking": false,
                                        "drinking": true,
                                        "allergies": "Peanuts, pollen",
                                        "pcod": false,
                                        "diabetes": true,
                                        "bloodPressure": false,
                                        "majorSurgery": "Knee replacement in 2018"   
                                  }
                                  
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "User"
                ],
                "parameters": [
                      {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "schema": {
                          "type": "number"
                        }
                      }
                ],
                "summary": "User by id ",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        }
        
    }
}